name: Build and Deploy .NET Application

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore ./TAREA13-AaronCondori/TAREA13-AaronCondori.csproj

      - name: Build application
        run: dotnet build ./TAREA13-AaronCondori/TAREA13-AaronCondori.csproj --configuration Release

      - name: Publish application
        run: dotnet publish ./TAREA13-AaronCondori/TAREA13-AaronCondori.csproj --configuration Release --output ./published
